### ISSUE TITLE
Test cascade 

### ISSUE THREAD

**Issue by LupusTheCanine** [dbaumgarten/yodk#101]
**Is your feature request related to a problem? Please describe.**
I started working on a script that implements linked list for fixed length strings. I wanted to implement tests to make validating code easier. My script has extensive internal state that I do not want to expose to other scripts to avoid collisions as well as prevent state coruption. I want to provide a sequence of test inputs that validate that the script is beaving corectly.

**Describe the solution you'd like**
I would like to see a variant of test case that doesn't reset scripts states.

**Describe alternatives you've considered**
Another alternative would be a test case that sends specified sequence of inputs instead of only setting initial state. Another posibility would be allowing internal state of a script to be set. I could also make internal state global but this would interfere with compilation and be error prone.

I think all above solutions are more labor intensive for a script developer than test case sequence.

**Additional context**
```
Example code
cases:
  - name: Initial Test
    # optional: global variables to set before running. ':' can be omitted
    stopwhen:
      lm: 0
    inputs:
      wp: "AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHH"
      lm: 5
    # optional: expected value for global variables after running
    # it he values after execution the scipts do not match the values here, the test fails
    outputs:
        lm: 0
        cws: "HHHH"
  - name: backwards no more #here yolol internal state is reset but I would like execution to continue
    stopwhen:
      lm: 0
    inputs:
      lm: -1
    outputs:
      cws: "HHHH"
```
